### ISSUE TITLE
addGroup doesn't return Group

### ISSUE THREAD

**Issue by Spenhouet** [gmessner/gitlab4j-api#109]
The `addGroup` method of the `GroupApi` doesn't return the created `Group` at the moment.
The GitLab API does return the created group. It would be nice if the `addGroup` method would return a `Group` object.

https://docs.gitlab.com/ce/api/groups.html#new-group

_Additionally I did see that the parameters given in the current implementation of `addGroup` doesn't match the parameters of the GitLab API documentation. Not sure if this is intentional.
To be precise, the following parameters are not mentioned in the documentation but are implemented in the `addGroup` method: `membership_lock`, `share_with_group_lock`, `shared_runners_minutes_limit`_

**Comment by gmessner** [comment]
I have modified the addGroup() methods to return the created Group instance and created new addGroup() and updateGroup() methods with the parameters as specified in the newer docs.  The reason that the additional parameters where there was because they use to be valid parameters.  I have deprecatred these methods and created new ones matching the current docs.

Changing the API calls is something that I wish GitLab would do a little less often, makes it difficult to stay on top of things.
