### ISSUE TITLE
Connection timed out: connect

### ISSUE THREAD

**Issue by ricky001** [gmessner/gitlab4j-api#185]
While running the script on GitLab Enterprise the below error occurs
org.gitlab4j.api.GitLabApiException: java.net.ConnectException: Connection timed out: connect,
Why this error occurs

**Comment by gmessner** [comment]
@ricky001 
This can be for many reasons, but typically it is because of one of the following:
- The hostname of the server you are trying to connect to is not correct
- The server is not reachable or is down.

You can verify both by simply using a browser pointed at:
http://[your-server-hostname]:[server-port-if-not-80]/api/v4

You should receive a 404 not found error.

**Comment by gmessner** [comment]
@ricky001 
It is also possible that GitLab may have blacklisted your IP address since you were also experiencing the "too many requests" error.

**Comment by ricky001** [comment]
Too many request error is for different GitLab Url

**Comment by gmessner** [comment]
@ricky001 
Did you verify that the GitLab server is reachable from your browser?

You can verify both by simply using a browser pointed at:
http://[your-server-hostname]:[server-port-if-not-80]/api/v4

You should receive a 404 not found error.  A 404 indicates that the server is up and the URL you went to is not found.  If you get a timeout or not reachable error then you have a problem that has nothing to do with this library.

**Comment by gmessner** [comment]
@ricky001 
I am assuming that you have resolved this, if not, please re-open the issue.
