### ISSUE TITLE
createFile bug

### ISSUE THREAD

**Issue by zhengrenjie** [gmessner/gitlab4j-api#197]
https://github.com/gmessner/gitlab4j-api/blob/69f26d017d4816fbe5e93d23b91d83280b9745df/src/main/java/org/gitlab4j/api/AbstractApi.java#L402
When i want to create a new file with empty content , a exception thrown . But gitlab web and gitlab api (has tested by postman)both allow the empty content. 
I think this might be a bug , but this method has too many associations( i can't fix it) .

**Comment by gmessner** [comment]
@zhengrenjie 
Because https://docs.gitlab.com/ee/api/repository_files.html#create-new-file-in-repository states that `content` is required, it was assumed that `content` could not be empty.  I have verified that the GitLab API accepts empty` content` and fixed both createFile() and updateFile() to allow for empty or whitespace only `content`.  Content cannot be null, but it can now be empty or whitespace only.

Release 4.8.24 is now available with the fix.  When you have a chance, please verify and close this issue.

**Comment by zhengrenjie** [comment]
That would be very grateful !
