### ISSUE TITLE
Please add "gitLabApi.getProjectApi().getProjects(int page, int perPage)" method

### ISSUE THREAD

**Issue by neillau24** [gmessner/gitlab4j-api#24]
Please add "gitLabApi.getProjectApi().getProjects(int page, int perPage)" method
thank you!

**Comment by gmessner** [comment]
I have been working on an Iterator implementation that encapsulates the paging of all calls to the API that support paging. For projects it would work like this:

```java
// Get a Pager instance that will page through the projects with 10 projects per page
Pager<Project> projectPager = gitlabApi.getProjectsApi().getProjectsPager(10);

// Iterate through the pages and print out the name and description
while (projectsPager.hasNext())) {

    List<Project> projects = projectsPager.next();
    for (Project project : projects) {
        System.out.println(project.getName() + " -: " + project.getDescription());
    }
}
```

Pager is a regular Iterator without remove() implemented. It pages over the available lists of objects by issuing the appropriate call to the GitLab API. It also has the following public non-Iterator methods:

```java
List<T> first();
int getItemsPerPage();
int getNumPages();
List<T> getPage(int pageNumber);
int getTotalItems();
List<T> last();
List<T> previous();
```
Would this functionality meet your needs instead of:

```java
gitLabApi.getProjectApi().getProjects(int page, int perPage) 
```

**Comment by neillau24** [comment]
I can not find  **gitlabApi.getProjectsApi().getProjectsPager(10);**

**Comment by gmessner** [comment]
You will not find it, this is just a proposal.  I wanted to get your feedback on it before it was implemented.

Since it might be a week or two before this is implemented I went ahead and added getProjects(int page, int perPage).  You'll find it in release 4.2.4.
