### ISSUE TITLE
Parser of GitLab error responses fails

### ISSUE THREAD

**Issue by mdeknowis** [gmessner/gitlab4j-api#260]
We are using `4.8.50` of  `gitlab4j-api`.

We experienced that GitLab returns errors e.g. in case of POST `api/v4/groups` as

```json
{"error":"path is missing"}
```
Hence `org.gitlab4j.api.GitLabApiException.GitLabApiException(Response)` fails to parse the body, because it only supports this structure:

```java
public class ErrorMessage {

    private String message;
...
}
```

So we have no chance to get the error message.

So it would be very helpful to support also `error`, so the `message` of `GitLabApiException` is filled with the error message.

**Comment by gmessner** [comment]
As per https://docs.gitlab.com/ee/api/#data-validation-and-error-reporting, all errors except 404 have this structure:
```
{ "message":"400 (Bad request) \"title\" not given" }
```
404 errors have this:
```
{ "error": "404 Not Found" }
```
If I understand, you are asking for GitLabApiException to add reading of response with the "error" field so that regardless of the error response it will always end up as message property of the GitLabApiException.

**Comment by mdeknowis** [comment]
That would be great. I'm not sure, if the error response is originally a bug on GitLab side.

But that was the response of our invalid request:

```txt
org.gitlab4j.api.GitLabApi               : 1 * Sending client request on thread http-nio-14080-exec-1
1 > POST https://xxx/api/v4/groups
1 > Accept: application/json
1 > Content-Type: application/x-www-form-urlencoded
1 > PRIVATE-TOKEN: xxx
name=managed-solutions&request_access_enabled=false

org.gitlab4j.api.GitLabApi               : 1 * Client response received on thread http-nio-14080-exec-1
1 < 400
1 < Cache-Control: no-cache
1 < Connection: keep-alive
1 < Content-Length: 27
1 < Content-Type: application/json
1 < Date: Thu, 25 Oct 2018 13:40:53 GMT
1 < Vary: Origin
1 < X-Content-Type-Options: nosniff
1 < X-Frame-Options: SAMEORIGIN
1 < X-Request-Id: xxx
1 < X-Runtime: 0.021161
{"error":"path is missing"}
```

**Comment by gmessner** [comment]
I will modify this so that it will provide either "message" or "error" content as a String using the message property, and add a new method called getGitLabError() that will return the whatever is present as an object, which could either be a ```String``` or a Jackson ```JsonNode```

**Comment by gmessner** [comment]
@mdeknowis 
After further examination of the documentation and actual return values, there are 3 possible things in the content when an exception occurs:

1) An attribute is missing "message" as a String (HTTP Status 400)
2) Validation error "message" as a Map<String, String[]> (HTTP Status 400)
3) Unknown route "error" as a String (HTTP Status 404)

I have also seen non 400 and 404 erros, like a 500, but I do not recall what the format was.  So my proposal would be as follows:

Modify ```getMessage()``` as follows:
Since ```getMessage()``` is from the base ```Exception``` class and must always return a ```String```, will return the content of the "message" or "error" field as a ```java.lang.String```

Add the following methods to ```GitLabApiException```:
```public boolean hasValidationErrors()``` 
```public Map<String, String[]> getValidationErrors()```

Making these mods will ensure all possibilites are covered and allows ```GitLabApiException``` to be easily used to display error messages in a UI for form validation etc...

**Comment by gmessner** [comment]
@mdeknowis 
I've released GitLab4J-API 4.8.52 with the functionality as described above.

**Comment by gmessner** [comment]
@mdeknowis 
If this addresses your issues, please close once verified.

**Comment by mdeknowis** [comment]
Thanks. Looks fine!
