### ISSUE TITLE
Is there a way to submit an issue through the API? 

### ISSUE THREAD

**Issue by chakan2** [gmessner/gitlab4j-api#69]
I've been scouring the API for a day or so now and can't seem to find out how to submit an issue. 

I looked at the NotesAPI and It looks like all the put / post methods are protected and inaccessible. 

Any help is much appreciated!

**Comment by gmessner** [comment]
Currently there is only minimal support for issues, you'll find the issue related methods in the ProjectApi.  Currently there is no support for adding, editing, moving, or subscribing to an issue.  Because of the number of issue related operation an IssueApi class would need to be defined and implemented.  

If this is not something you are able to do and contribute, let me know and I will schedule it for the next release, currently scheduled for 9/10/2017.

**Comment by redrainz** [comment]
hello, your project is good! I want to use it to create issue,but i don't find the API . I hope you could help me .

**Comment by gmessner** [comment]
This is in progress, will be released on 9/18/2017.

**Comment by gmessner** [comment]
The IssuesApi has been partially implemented and is available in release 4.5.0.  There are a few methods missing but it does have support for creating and updating issues.

**Comment by gmessner** [comment]
@chakan2 
@redrainz 
Just an FYI, there has been some enhancements to the IssuesApi in the just released GitLab4J-API version 4.6.0.
